# config.yml
settings:
  concurrency: 50  # High concurrency for faster processing
  fetchTimeout: 3000  # Timeout for fetching M3U files
  linkCheckTimeout: 2000  # Timeout for checking link activity
  batchSize: 100  # Number of links to check in a single batch
  outputDirPrefix: SpecialLinks  # Base name for output directories/files
  channelsPerFile: 2000  # Maximum number of channels per file

urls:
- http://fastream.xyz:8080/get.php?username=82526697&password=23082022&type=m3u&output=mpegts
- http://live.iptvtotaal.com:8000/get.php?username=513463512215&password=814362424133&type=m3u&output=mpegts

# Add more URLs here (up to 100)
